### ISSUE TITLE
Customize previewer

### ISSUE THREAD

**Issue by ElSargo** [kyoheiu/felix#126] opened 2022-10-24 06:22 UTC
It would be great to be able to change the app that creates the previews of text files, to something that does syntax highlighting such as bat or pistol

**Comment by kyoheiu** [comment] 2022-10-29 07:34
It's possible, and I created PR to add the syntax highlighting if possible #129.
I have to handle the panic caused by `syntect::util::split_at` so this PR is not completed yet.
And also, this PR could not yet let users choose their favorite theme (now it's set to base16-ocean.dark).
(BTW this PR is for `feature-horizontal-split` branch, which adds horizontal split screen by pressing `s`)

**Comment by kyoheiu** [comment] 2022-10-29 07:36
I'm not certain it's worth adding the syntax highlighting, but anyway will continue implementing it.

**Comment by kyoheiu** [comment] 2022-10-29 09:27
Related: https://github.com/trishume/syntect/issues/453

**Comment by kyoheiu** [comment] 2022-11-04 21:45
#129 merged to develop branch. After some debugging it will be released.

**Comment by kyoheiu** [comment] 2022-11-11 08:54
#141 merged

**Closed by kyoheiu** 2022-11-11 08:54 UTC
Labels: enhancement
